module.exports = {
    insertBill: `insert into bill set ?`,
    insertBillDetails: `insert into bill_detail set ?`,
    queryListBillByUserID: `SELECT bill.bill_id ,bill.status , bill.total_price ,bill.total_product ,bill.created_at FROM bill WHERE user_id=?`,
    queryProductListBillUser: `SELECT bill_detail.product_name , bill_detail.size , bill_detail.quantity , bill_detail.price , bill_detail.price_sale , product.product_image  FROM bill_detail ,product WHERE bill_detail.product_name = product.product_name AND  bill_id = ? LIMIT 1`,
    queryBillByBillID: `SELECT bill.bill_id,bill.status, user.phone, user.user_name, bill.address , bill.created_at ,bill.updated_at ,bill.total_price,bill.total_product ,bill.discount_voucher_price ,bill.cancellation_reason , bill.feedback , bill.return_request ,bill.feedback_by_store ,payment_status FROM bill , user WHERE bill.user_id = user.user_id AND bill.bill_id=?`,
    queryBillDetailByBillID: `SELECT bill_detail.product_name, bill_detail.size, bill_detail.quantity, bill_detail.price ,bill_detail.price_sale, product.product_image FROM bill_detail , product WHERE bill_detail.product_name = product.product_name AND bill_id= ?`,
    queryBill: `SELECT * FROM bill where bill_id=?`,
    queryListID: `SELECT bill_id FROM bill `,
    updateStatusBill: `UPDATE bill SET status = "Yêu Cầu Hủy" WHERE bill_id=?`,
    updateBill: 'UPDATE bill SET status = ? , cancellation_reason= ? WHERE bill_id= ? ',
    updateFeedBack: 'UPDATE bill SET  feedback = ? WHERE bill_id = ? ',
    updateReturnRequest: 'UPDATE bill SET  status = ? , return_request = ? WHERE bill_id = ? ',
    updateFeedBackStore: 'UPDATE bill SET  status= ? , feedback_by_store= ? WHERE bill_id = ? ',
    queryAllBill:
        'SELECT  bill.bill_id, user.phone,user.user_id, user.user_name,bill.address,bill.total_price,bill.total_product,bill.status,bill.created_at  FROM bill,user WHERE bill.user_id=user.user_id  ORDER BY bill.created_at DESC',
    queryBillById: `SELECT *FROM bill where bill_id=?`,
    updateStatusBillWeb: `UPDATE bill SET status= ?  WHERE bill_id= ?`,
    updateBillDone: `UPDATE bill SET status= ? ,done=? , updated_at= ? WHERE bill_id= ?`,
    queryListRevenueByYear: `SELECT MONTH(created_at) AS Month, SUM(total_price) AS Revenue FROM bill WHERE status="Hoàn Thành" AND YEAR(created_at) = ? GROUP BY MONTH(created_at) ORDER BY MONTH(created_at) ASC`,
    queryTop10User: `SELECT user.user_id , user.user_name, COUNT(bill.bill_id) as billCount ,SUM(bill.total_price) as totalAmountSpent FROM bill ,user WHERE user.user_id = bill.user_id AND status="Hoàn Thành" GROUP BY user_id ORDER BY COUNT(bill_id) DESC LIMIT 0,10`,
    queryTongDoanhThu: `SELECT SUM(total_price) as TongDoanhThu FROM bill WHERE status="Hoàn Thành" `,
    queryDonDangXuLy: `SELECT COUNT(bill_id) as DonDangXuLy FROM bill WHERE status="Chờ Xác Nhận" OR status="Yêu Cầu Hủy Đơn" OR status="Yêu Cầu Hoàn Đơn" OR status="Đang Giao"`,
    queryBillWaiting: `SELECT COUNT(bill_id) as billWaiting FROM bill WHERE status="Chờ Xác Nhận" `,
    queryBillDelivering: `SELECT COUNT(bill_id) as billDelivering FROM bill WHERE status="Đang Giao" `,
    queryDonHoanThanh: `SELECT COUNT(bill_id) as DonDaGiao FROM bill WHERE status="Hoàn Thành" `,
    queryBillRequestCancellationORRefund: `SELECT COUNT(bill_id) as billRequestCancellationORRefund FROM bill WHERE status="Yêu Cầu Hủy Đơn" OR status="Yêu Cầu Hoàn Đơn" `,
    queryDonThatBai: `SELECT COUNT(bill_id) as DonThatBai FROM bill WHERE status="Đã Hủy" OR status="Đã Hoàn" OR status="Thất Bại" OR status="Từ Chối Đơn"`,
    queryListBillWaitingByMonth: `SELECT MONTH(created_at) AS Month, COUNT(bill_id) AS billWaiting FROM bill WHERE status="Chờ Xác Nhận" AND YEAR(created_at) = 2022 GROUP BY MONTH(created_at) ORDER BY MONTH(created_at) ASC`,
    queryListBillDeliveringByMonth: `SELECT MONTH(created_at) AS Month, COUNT(bill_id) AS billDelivering FROM bill WHERE status="Đang Giao" AND YEAR(created_at) = 2022 GROUP BY MONTH(created_at) ORDER BY MONTH(created_at) ASC`,
    queryListBillDoneByMonth: `SELECT MONTH(created_at) AS Month, COUNT(bill_id) AS billDone FROM bill WHERE status="Hoàn Thành" AND YEAR(created_at) = 2022 GROUP BY MONTH(created_at) ORDER BY MONTH(created_at) ASC`,
    queryListBillRequestCancellationORRefundByMonth: `SELECT MONTH(created_at) AS Month, COUNT(bill_id) AS billRequestCancellationORRefund FROM bill WHERE (status="Yêu Cầu Hủy Đơn" OR status="Yêu Cầu Hoàn Đơn") AND YEAR(created_at) = 2022 GROUP BY MONTH(created_at) ORDER BY MONTH(created_at) ASC`,
    queryListBillFailByMonth: `SELECT MONTH(created_at) AS Month, COUNT(bill_id) AS billFail FROM bill WHERE(status="Đã Hủy" OR status="Đã Hoàn" OR status="Thất Bại" OR status="Từ Chối Đơn") AND YEAR(created_at) = 2022 GROUP BY MONTH(created_at) ORDER BY MONTH(created_at) ASC`,
};
